
# config/_default/hugo.toml
theme = "blowfish"
baseURL = "https://giantleapsite.netlify.app/"

languageCode = "it"
defaultContentLanguage = "it"

enableRobotsTXT = true
summaryLength = 0
enableEmoji = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    noClasses = false
