# config/_default/hugo.toml
theme = "blowfish"
baseURL = "https://giantleapsite.netlify.app/"

languageCode = "it"
defaultContentLanguage = "it"

disableKinds = ["taxonomy", "term"]

enableRobotsTXT = true
summaryLength = 0
enableEmoji = false

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    noClasses = false

[module]
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "content/_index.md"
    target = "content/_index.md"
  [[module.mounts]]
    source = "content/_index.it.md"
    target = "content/_index.it.md"
  [[module.mounts]]
    source = "content/_index.en.md"
    target = "content/_index.en.md"
  [[module.mounts]]
    source = "content/chi-siamo"
    target = "content/chi-siamo"
  [[module.mounts]]
    source = "content/diario-di-bordo"
    target = "content/diario-di-bordo"
  [[module.mounts]]
    source = "content/dipartimenti"
    target = "content/dipartimenti"
  [[module.mounts]]
    source = "content/join-us"
    target = "content/join-us"
  [[module.mounts]]
    source = "content/leapcon"
    target = "content/leapcon"
  [[module.mounts]]
    source = "content/staff"
    target = "content/staff"
