
# config/_default/menus.it.toml

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Chi Siamo"
  pageRef = "chi-siamo"
  weight = 20

[[main]]
  name = "Join Us"
  pageRef = "join-us"
  weight = 30

[[main]]
  name = "Galleria"
  pageRef = "galleria"
  weight = 40

[[main]]
  name = "Diario di Bordo"
  pageRef = "diario-di-bordo"
  weight = 50

[[main]]
  name = "LeapCon"
  pageRef = "leapcon"
  weight = 60

[[main]]
  name = "Staff"
  pageRef = "staff"
  weight = 70

[[footer]]
  name = "Home"
  url = "/"
  weight = 10

[[footer]]
  name = "Diario di Bordo"
  pageRef = "diario-di-bordo"
  weight = 20
