[[main]]
  name = "Home"
  url = "/en/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "chi-siamo"
  weight = 20

[[main]]
  name = "Join us"
  pageRef = "join-us"
  weight = 30

[[main]]
  name = "Gallery"
  pageRef = "galleria"
  weight = 40

[[main]]
  name = "Logbook"
  pageRef = "diario-di-bordo"
  weight = 50

[[main]]
  name = "Events"
  pageRef = "leapcon"
  weight = 60

[[main]]
  name = "Staff"
  pageRef = "staff"
  weight = 70

[[footer]]
  name = "Home"
  url = "/en/"
  weight = 10

[[footer]]
  name = "Logbook"
  pageRef = "diario-di-bordo"
  weight = 20
