
# config/_default/menus.it.toml

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Chi siamo"
  pageRef = "chi-siamo"
  weight = 20

[[main]]
  name = "Join us"
  pageRef = "join-us"
  weight = 30

[[main]]
  name = "Dipartimenti"
  pageRef = "dipartimenti"
  weight = 40

[[main]]
  name = "Diario di bordo"
  pageRef = "diario-di-bordo"
  weight = 50

[[main]]
  name = "Eventi"
  pageRef = "leapcon"
  weight = 60

[[main]]
  name = "Staff"
  pageRef = "staff"
  weight = 70

[[footer]]
  name = "Home"
  url = "/"
  weight = 10

[[footer]]
  name = "Diario di bordo"
  pageRef = "diario-di-bordo"
  weight = 20
