
# config/_default/params.toml
colorScheme = "giantleap"

defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = true

highlightCurrentMenuArea = true
mainSections = ["diario-di-bordo"]

[header]
  layout = "fixed"
  showTitle = false
  showAppearanceSwitcher = false
  showLanguageSwitcher = false

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "custom"
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = "/diario-di-bordo/"

[article]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showTableOfContents = true
  showReadingTime = true
  showWordCount = false

[list]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showSummary = true
  showCards = true
  cardView = true
  groupByYear = true
